<?php
include 'includes/search-results.php';
include 'includes/result.php';

define("PDC_SERVERADRESS", 'http://localhost:8080');

function ddb_pdc_menu() {
  $items = array();

 
$items['public-domain-calculator'] = array( // creates a link for the PDC search form
    'title' => 'Public Domain Calculator', // page title
    'description' => 'Deutsche Digitale Bibliothek - Public Domain Calculator', // page description
    'page callback' => 'drupal_get_form', // function that creates a (form) content for this page
    'page arguments' => array('ddb_pdc_form'), // function that provides input for the drupal_get_form function - eg. drupal_get_form(ddb_pdc_form);
    'access callback' => TRUE // permission
  );

$items['search-results/%'] = // % will be replaced by page arguments
  array(
    'title' => 'Public Domain Calculator results',
    'page callback' => 'ddb_pdc_search_results',
	'access callback' => TRUE,
	'page arguments' => array(1), // searchterm as argument for the function ddb_pdc_controller
	'type' => MENU_CALLBACK,
  );  
  
$items['pdc-result/%'] = // % will be replaced by page arguments
  array(
    'title' => 'Public Domain Calculator results',
    'page callback' => 'ddb_pdc_result',
	'access callback' => TRUE,
	'page arguments' => array(1), // searchterm as argument for the function ddb_pdc_controller
	'type' => MENU_CALLBACK,
  ); 
  
  return $items;
}

function
ddb_pdc_form($form, &$form_state) {
 $form = array();
 $form['#redirect'] = 'public-domain-calculator-results';
 
$form['ddb_title'] = array(
    '#type' => 'textfield',
    '#label' => 'Geben Sie hier den Titel ein!',
    '#required' => TRUE,
  );
 
$form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Calculate!'),
  );
 
  return $form;
}

function
ddb_pdc_form_validate($form, &$form_state) { // to validate input fields
  
}

function
ddb_pdc_form_submit($form, &$form_state) {
	//drupal_set_message(t("Author: @author, Titel: @title", array('@author' => $form_state['values']['ddb_author'], '@title' => $form_state['values']['ddb_title'])));

	drupal_goto('search-results/' .  $form_state['values']['ddb_title']);
}

function ddb_pdc_http_request($request, $inputdata){
	
  	$options = array(
    'method' => 'POST', // HTTP Request Type
    'data' => $inputdata, // Parameters to pass to URL
	'timeout' => 45,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  
   $result = drupal_http_request(PDC_SERVERADRESS . $request , $options); 
   
  return $result;	
  
}